{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ModelType", "label": "ModelType", "query": { "query": "query_result(model_type)" } },
   {
    "name": "Gender",
    "label": "Gender",
    "query": {
     "query": "query_result(gender_distribution)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gender Distribution",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gender_distribution", "legendFormat": "{{gender}}" }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Prediction Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "requests_per_minute_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(requests_per_minute_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "rate(errors_total[1m]) / rate(requests_per_minute_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "rate(inference_latency_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(request_latency_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}